version: "3.9"

services:
  milvus:
    image: milvusdb/milvus:v2.4.4-20240709-d2da738
    container_name: semcode-milvus
    command: ["milvus", "run", "standalone"]
    environment:
      MILVUS_LOGGER_CONSOLE_LEVEL: warn
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus-data:/var/lib/milvus

  api:
    build:
      context: .
    command: semcode-api
    depends_on:
      - milvus
    environment:
      SEMCODE_CONFIG_PATH: /config/semcode_settings.toml
    ports:
      - "8000:8000"
    volumes:
      - ./semcode_settings.toml:/config/semcode_settings.toml:ro
      - ./workspace:/workspace

  streamlit:
    build:
      context: .
    command: semcode-streamlit
    depends_on:
      - api
    environment:
      SEMCODE_CONFIG_PATH: /config/semcode_settings.toml
    ports:
      - "8501:8501"
    volumes:
      - ./semcode_settings.toml:/config/semcode_settings.toml:ro
      - ./workspace:/workspace

volumes:
  milvus-data:
