name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            uv.lock

      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: venv
          key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install project (dev extras)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make install-ui

      - name: Lint
        run: make lint

      - name: Type check
        run: make typecheck

      - name: tests
        run: make test
